config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: "homes#top"
    get 'dashboards', to: 'dashboards#index'
    resources :groups do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :maintenances do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :maintenance_comments, only: [:index, :destroy]do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :users do
      member do
        patch :restore
      end
      collection do
        get :deleted_index
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions' 
    }

    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end

    resources :users, only: [:index, :show, :edit, :update] do
      delete 'unsubscribe', on: :member
    end

    root to: "homes#top"

    resources :maintenances, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :maintenance_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :favorites, only: [:index]
    resources :cars, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :fuel_efficiencies, only: [:new, :create, :index, :show, :edit, :update, :destroy]

    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resources :group_users, only: [:create, :destroy]
      resources :event_notices, only: [:new, :create]
      get "event_notices" => "event_notices#sent"
      member do
        delete 'remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'
      end
      resources :requests, only: [:create, :update]
    end

    get '/search', to: 'searches#search'
  end
end

app/models/maintenance_comment.rb
class MaintenanceComment < ApplicationRecord
  belongs_to :user
  belongs_to :maintenance
  
  validates :comment, presence: true

  default_scope { where(deleted_at: nil) }
  scope :with_deleted, -> { unscope(where: :deleted_at) }

  def soft_delete
    update(deleted_at: Time.current)
  end

  def restore
    update(deleted_at: nil)
  end

  def deleted?
    deleted_at.present?
  end
end

app/controllers/admin/maintenance_comments_controller.rb
class Admin::MaintenanceCommentsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @maintenance_comments = MaintenanceComment.with_deleted
  end

  def destroy
  comment = MaintenanceComment.unscoped.find_by(id: params[:id])

  if comment
    comment.soft_delete
    flash[:success] = "コメントは削除されました。"
  else
    flash[:error] = "コメントが見つかりませんでした。" 
  end

  redirect_to admin_maintenance_comments_path
  end


  def deleted_index
    @comments = MaintenanceComment.with_deleted.where.not(deleted_at: nil)
  end

  def restore
    @comment = MaintenanceComment.with_deleted.find(params[:id])
    @comment.restore
    redirect_to admin_maintenance_comments_path, notice: "コメントを復元しました。"
  end

  private
  def maintenance_comment_params
    params.require(:maintenance_comment).permit(:comment)
  end
end

app/controllers/maintenance_comments_controller.rb
class MaintenanceCommentsController < ApplicationController
  def create
    maintenance = Maintenance.find(params[:maintenance_id])
    comment = current_user.maintenance_comments.new(maintenance_comment_params)
    comment.maintenance_id = maintenance.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    MaintenanceComment.find_by(id: params[:id], maintenance_id: params[:maintenance_id]).destroy
    redirect_to request.referer
  end

  private
  def maintenance_comment_params
    params.require(:maintenance_comment).permit(:comment)
  end
end

app/helpers/admin/maintenance_comments_helper.rb
module Admin::MaintenanceCommentsHelper
end

app/helpers/maintenance_comments_helper.rb
module MaintenanceCommentsHelper
end

app/views/admin/maintenance_comments/_index.html.erb
<table class="table table-honer table-inverse">
  <thead>
    <tr>
      <th>ユーザー名</th>
      <th>コメント</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @maintenance_comments.each do |comment| %>
      <tr class="<%= 'text-muted' if comment.deleted? %>">
              <td><%= comment.user&.name || "退会ユーザー" %></td>
              <td><%= comment.comment %></td>
              <td>
                <% if comment.deleted? %>
                  <%= link_to "復元", restore_admin_maintenance_comment_path(comment), method: :patch, class: "btn btn-success" %>
                <% else %>
                  <%= link_to "削除", admin_maintenance_comment_path(comment),method: :delete, data: { confirm: "削除しますか？" }, class: "btn btn-danger" %>
                <% end %>
              </td>
            </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/maintenance_comments/deleted_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>削除済みコメント一覧</h1>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>ユーザー</th>
            <th>コメント内容</th>
            <th>削除日時</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @comments.each do |c| %>
            <tr class="table-secondary">
              <td><%= c.id %></td>
              <td><%= c.user.name %></td>
              <td><%= c.comment %></td>
              <td><%= c.deleted_at %></td>
              <td>
                <%= link_to "復元", restore_admin_maintenance_comment_path(c),method: :patch, class: "btn btn-success" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/maintenance_comments/index.html.erb
<p id="notice"><%= notice %></p>

<% if flash[:alert].present? %>
  <p class="alert"><%= flash[:alert] %></p>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Admin's Comment List</h1>
      <%= link_to "削除済みコメント一覧", deleted_index_admin_maintenance_comments_path, class: "btn btn-secondary" %>
      <table class="table table-honer table-inverse">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>コメント</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @maintenance_comments.each do |comment| %>
            <tr class="<%= 'table-danger' if comment.deleted? %>">
              <td><%= comment.user&.name || "退会ユーザー" %></td>
              <td><%= comment.comment %></td>
              <td>
                <% if comment.deleted? %>
                  <%= link_to "復元", restore_admin_maintenance_comment_path(comment), method: :patch, class: "btn btn-success" %>
                <% else %>
                  <%= link_to "削除", admin_maintenance_comment_path(comment),method: :delete, data: { confirm: "削除しますか？" }, class: "btn btn-danger" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>