config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: "homes#top"
    get 'dashboards', to: 'dashboards#index'
    resources :groups do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :maintenances do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :maintenance_comments, only: [:index, :destroy]do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :users do
      member do
        patch :restore
      end
      collection do
        get :deleted_index
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions' 
    }

    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end

    resources :users, only: [:index, :show, :edit, :update] do
      delete 'unsubscribe', on: :member
    end

    root to: "homes#top"

    resources :maintenances, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :maintenance_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :favorites, only: [:index]
    resources :cars, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :fuel_efficiencies, only: [:new, :create, :index, :show, :edit, :update, :destroy]

    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resources :group_users, only: [:create, :destroy]
      resources :event_notices, only: [:new, :create]
      get "event_notices" => "event_notices#sent"
      member do
        delete 'remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'
      end
      resources :requests, only: [:create, :update]
    end

    get '/search', to: 'searches#search'
  end
end

app/models/maintenance.rb
class Maintenance < ApplicationRecord

  enum is_active: { draft: false, published: true }

  belongs_to :user
  belongs_to :car
  has_many_attached :images, dependent: :destroy
  has_one_attached :tool_images, dependent: :destroy
  has_many :work_descriptions, dependent: :destroy
  has_many :maintenance_comments
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :maintenance_day, presence: true
  validates :maintenance, presence: true
  validates :work_difficulty, presence: true

  default_scope { where(deleted_at: nil) }
  scope :with_deleted, -> { unscope(where: :deleted_at) }

  def soft_delete
    update_column(:deleted_at, Time.current)
  end

  def restore
    update_column(:deleted_at, nil)
  end

  def deleted?
    deleted_at.present?
  end

  def get_tool_images
    if tool_images
      tool_images
    else
      ActionController::Base.helpers.asset_path('no_image.jpg')
    end
  end
  def get_images
    if images.attached?
      images
    else
      ActionController::Base.helpers.asset_path('no_image.jpg')
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Maintenance.joins(:car).where('maintenances.title LIKE ? OR cars.car_name LIKE ?', "%#{content}%", "%#{content}%")
    elsif method == 'forward'
      Maintenance.joins(:car).where('maintenances.title LIKE ? OR cars.car_name LIKE ?', "#{content}%", "#{content}%")
    elsif method == 'backward'
      Maintenance.joins(:car).where('maintenances.title LIKE ? OR cars.car_name LIKE ?', "%#{content}", "%#{content}")
    else
      Maintenance.joins(:car).where('maintenances.title LIKE ? OR cars.car_name LIKE ?', "%#{content}%", "%#{content}%")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/controllers/admin/maintenances_controller.rb
class Admin::MaintenancesController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @maintenances = Maintenance.unscoped.all
  end

  def show
    @maintenance = Maintenance.find(params[:id])
    @maintenance_comments = @maintenance.maintenance_comments.with_deleted
  end


  def destroy
    @maintenance = Maintenance.find(params[:id])
    @maintenance.soft_delete
    redirect_to admin_maintenances_path, notice: "メンテナンス情報の削除に成功しました。"
  end

  def deleted_index
    @maintenances = Maintenance.unscoped.where.not(deleted_at: nil)
  end

  def restore
    @maintenance = Maintenance.unscoped.find(params[:id])
    @maintenance.restore
    redirect_to admin_maintenances_path, notice: "メンテナンスを復元しました"
  end

  private

  def maintenance_params
    params.require(:maintenance).permit(:title, :maintenance_day, :maintenance, :work_difficulty, :work_time, :work_pay, :tool_images, :images, :related_information, :work_description, :car_id)
  end
end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController
  before_action :authenticate_user!

  def new
    @maintenance = Maintenance.new
  end

  def create
    @maintenance = Maintenance.new(maintenance_params)
    @maintenance.user_id = current_user.id


    if @maintenance.save
      flash[:notice] = "You have created maintenance successfully."
      redirect_to maintenance_path(@maintenance)
    else
      flash[:notice] = "You have not created maintenance successfully."
      render 'new'
    end
  end

  def index
    @maintenances = Maintenance.all
  end

  def show
    @maintenance = Maintenance.find(params[:id])
    @user = @maintenance.user
    @maintenance_new = Maintenance.new
    @maintenance_comment = MaintenanceComment.new
  end

  def edit
    @maintenance = Maintenance.find(params[:id])
    if @maintenance.user != current_user
      flash[:notice] = "You cannot renew another user's maintenance."
      redirect_to maintenances_path
    end
  end

  def update
    @maintenance = Maintenance.find(params[:id])
    if @maintenance.update(maintenance_params)
      flash[:notice] = "You have update maintenance successfully"
      redirect_to @maintenance
    else
      flash[:notice] = "You have not update maintenance successfully."
      render 'index'
    end
  end

  def destroy
    @maintenance = Maintenance.find(params[:id])
    if @maintenance.user == current_user
      @maintenance.destroy
      redirect_to maintenances_path, notice: "Maintenance deleted"
    else
      redirect_to maintenances_path, alert: "You do not have permission to delete other users' maintenance."
    end
  end

  private

  def maintenance_params
    params.require(:maintenance).permit(:title, :maintenance_day, :maintenance, :work_difficulty, :work_time, :work_pay, :tool_images, :images , :related_information, :work_description)
  end
end

app/helpers/admin/maintenances_helper.rb
module Admin::MaintenancesHelper
end

app/helpers/maintenances_helper.rb
module MaintenancesHelper
end

app/views/admin/maintenances/deleted_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>削除済みメンテナンス一覧</h1>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>ユーザー</th>
            <th>削除日時</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @maintenances.each do |m| %>
            <tr class="table-secondary">
              <td><%= m.title %></td>
              <td><%= m.user.name %></td>
              <td><%= m.deleted_at %></td>
              <td>
                <%= link_to "復元", restore_admin_maintenance_path(m), method: :patch,class: "btn btn-success" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/maintenances/index.html.erb
<p id="notice"><%= notice %></p>

<% if flash[:alert].present? %>
  <p class="alert"><%= flash[:alert] %></p>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Admin's Maintenance List</h1>
      <%= link_to "削除済みメンテナンス一覧", deleted_index_admin_maintenances_path, class: "btn btn-secondary" %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>公開状態</th>
            <th>車種</th>
            <th>タイトル</th>
            <th>作業日</th>
            <th>作業内容</th>
            <th>作業難易度</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% if @maintenances.present? %>
            <% @maintenances.each do |maintenance| %>
              <tr class="<%= 'table-danger' if maintenance.deleted_at.present? %>">
                <td>
                  <% if maintenance.published? %>
                    <span class="badge bg-success">公開</span>
                  <% else %>
                    <span class="badge bg-secondary">非公開</span>
                  <% end %>
                </td>
                <td><%= maintenance.car&.car_name %></td>
                <td><%= maintenance.title %></td>
                <td><%= maintenance.maintenance_day %></td>
                <td><%= maintenance.maintenance %></td>
                <td><%= maintenance.work_difficulty %></td>
                <td>
                  <% if maintenance.deleted_at.present? %>
                    <%= link_to '復元', restore_admin_maintenance_path(maintenance),method: :patch,class: 'btn btn-success' %>
                  <% else %>
                    <%= link_to '詳細', admin_maintenance_path(maintenance), class: 'btn btn-info' %>
                    <%= link_to '削除', admin_maintenance_path(maintenance),method: :delete,data: { confirm: '本当に削除しますか？' },class: 'btn btn-danger' %>
                  <% end %>
                </td>
                <td>コメント数: <%= maintenance.maintenance_comments.count %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/maintenances/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <p class="w-25"><strong>車両画像:</strong><%= image_tag @maintenance.car.car_image, class:"img-fluid", alt:"Car Image" %></p>
      <p><strong>公開状態:</strong>
        <% if @maintenance.published? %>
          <span class="badge bg-success">公開</span>
        <% else %>
          <span class="badge bg-secondary">非公開</span>
        <% end %>
      </p>
      <p><strong>車種:</strong><%= @maintenance.car.car_name %></p>
      <p><strong>タイトル:</strong><%= @maintenance.title %></p>
      <p><strong>作業日:</strong> <%= @maintenance.maintenance_day %></p>
      <p><strong>作業内容:</strong> <%= @maintenance.maintenance %></p>
      <p><strong>作業難易度:</strong> <%= @maintenance.work_difficulty %></p>
      <p><strong>使用工具画像:</strong>
        <% if @maintenance.get_tool_images.present? %>
          <%= image_tag @maintenance.get_tool_images, class: "img-fluid w-25", alt: "Tool Image" %>
        <% else %>
          <img src="<%= asset_path('no_image.jpg') %>" class="img-fluid" alt="No Image">
        <% end %>
      </p>
      <p><strong>作業時間:</strong><%= @maintenance.work_time %></p>
      <p><strong>作業料金:</strong><%= @maintenance.work_pay %></p>

      <p><strong>作業画像:</strong>
        <% if @maintenance.images.present? %>
          <% @maintenance.images.each do |image| %>
            <%= image_tag url_for(image), class: "img-thumbnail", style: "width: 25%;" %>
          <% end %>
        <% else %>
          <img src="<%= asset_path('no_image.jpg') %>" class="img-fluid" alt="No Image">
        <% end %>
      </p>
      <p><strong>作業説明:</strong><%= @maintenance.work_description %></p>
      <p><strong>関連URL:</strong> <%= @maintenance.related_information %></p>
      <%= link_to "一覧", admin_maintenances_path, class: "btn btn-secondary" %>
      <%= link_to '削除', admin_maintenance_path(@maintenance),method: :delete,data: { confirm: '本当に削除しますか？' },class: 'btn btn-danger' %>
    </div>
    <div class='col-md-6'>
      <table>
        <tr>
         <td>コメント数: <%= @maintenance.maintenance_comments.count %></td>
          <% if @maintenance.user == current_user %><% end %>
        </tr>
      </table>

      <%= render "admin/maintenance_comments/index", maintenance: @maintenance %>

      </div>
  </div>
</div>