config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: "homes#top"
    get 'dashboards', to: 'dashboards#index'
    resources :groups do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :maintenances do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :maintenance_comments, only: [:index, :destroy]do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :users do
      member do
        patch :restore
      end
      collection do
        get :deleted_index
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions' 
    }

    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end

    resources :users, only: [:index, :show, :edit, :update] do
      delete 'unsubscribe', on: :member
    end

    root to: "homes#top"

    resources :maintenances, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :maintenance_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :favorites, only: [:index]
    resources :cars, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :fuel_efficiencies, only: [:new, :create, :index, :show, :edit, :update, :destroy]

    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resources :group_users, only: [:create, :destroy]
      resources :event_notices, only: [:new, :create]
      get "event_notices" => "event_notices#sent"
      member do
        delete 'remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'
      end
      resources :requests, only: [:create, :update]
    end

    get '/search', to: 'searches#search'
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many_attached :group_image
  belongs_to :owner, class_name: 'User'

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user
  has_many :requests, dependent: :destroy

  validates :group_name, presence:true
  validates :group_introduction, presence:true
  validates :group_introduction, length: { maximum: 100 }
  validates :group_rules, length: { maximum: 200 }

  default_scope { where(deleted_at: nil) }
  scope :with_deleted, -> { unscope(where: :deleted_at) }

  def soft_delete
    update(deleted_at: Time.current)
  end

  def restore
    if owner_id.present?
      owner = User.unscoped.find_by(id: owner_id)
      owner.restore if owner&.deleted?
    end
  
    update(deleted_at: nil)
  end

  def deleted?
    deleted_at.present?
  end

  def get_group_image
    if group_image.attached?
      group_image
    else
      ActionController::Base.helpers.asset_path('no_image.jpg')
    end
  end

  def is_owner_by?(user)
    return false if owner.nil? || user.nil?
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Group.where(group_name: content)
    elsif method == 'forward'
      Group.where('group_name LIKE ?', content + '%')
    elsif method == 'backward'
      Group.where('group_name LIKE ?', '%' + content)
    else
      Group.where('group_name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_group, only: [:edit, :update, :destroy]
  layout 'admin'

  def index
    @groups = Group.unscoped.all
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to admin_groups_path, notice: 'グループ情報が更新されました。'
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.soft_delete
    redirect_to admin_groups_path, notice: 'グループを削除しました。'
  end

  def deleted_index
    @groups = Group.unscoped.where.not(deleted_at: nil)
  end

  def restore
    @group = Group.unscoped.find(params[:id])
    if @group.restore
      redirect_to admin_groups_path, notice: "グループを復元しました"
    else
      redirect_to admin_groups_path, alert: "復元に失敗: #{@group.errors.full_messages.join(', ')}"
    end
  end

  private

  def set_group
    @group = Group.unscoped.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:group_name, :group_introduction, :group_image, :group_theme, :group_rules)
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/admin/groups/deleted_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>削除済みグループ一覧</h1>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>グループ名</th>
            <th>削除日時</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |g| %>
            <tr class="table-secondary">
              <td><%= g.group_name %></td>
              <td><%= g.deleted_at %></td>
              <td>
                <%= link_to "復元", restore_admin_group_path(g),method: :patch, class: "btn btn-success" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/groups/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>Admin Editing Groups</h1>

      <%= form_for(@group, url: admin_group_path(@group), method: :patch) do |f| %>
        <div class="form-group">
          <%= f.label :group_name %>
          <%= f.text_field :group_name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :group_introduction %>
          <%= f.text_area :group_introduction, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :group_image %>
          <%= f.file_field :group_image, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :group_theme %>
          <%= f.text_field :group_theme, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :group_rules %>
          <%= f.text_area :group_rules, class: 'form-control' %>
        </div>
        
        <div class="actions">
          <%= f.submit '更新', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/groups/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>All Group List</h1>
      <%= link_to "削除済みグループ一覧", deleted_index_admin_groups_path, class: "btn btn-secondary" %>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th>Group Image</th>
            <th>Group Name</th>
            <th>Introduction</th>
            <th>Theme</th>
            <th>Rules</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr class="<%= 'table-danger' if group.deleted? %>">
              <td><%= image_tag url_for(group.group_image.first), size: '300x300' %></td>
              <td><%= group.group_name %></td>
              <td><%= group.group_introduction %></td>
              <td><%= group.group_theme %></td>
              <td><%= group.group_rules %></td>
              <td><%= link_to '編集', edit_admin_group_path(group), class: "group_#{group.id} btn btn-primary" %></td>
              <td>
                <% if group.deleted? %>
                  <%= link_to "復元", restore_admin_group_path(group), method: :patch, class: "btn btn-success" %>
                <% else %>
                  <%= link_to "削除", admin_group_path(group), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>