config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    root to: "homes#top"
    get 'dashboards', to: 'dashboards#index'
    resources :groups do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :maintenances do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :maintenance_comments, only: [:index, :destroy]do
      collection do
        get :deleted_index
      end
      member do
        patch :restore
      end
    end
    resources :users do
      member do
        patch :restore
      end
      collection do
        get :deleted_index
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: :public do
    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions' 
    }

    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end

    resources :users, only: [:index, :show, :edit, :update] do
      delete 'unsubscribe', on: :member
    end

    root to: "homes#top"

    resources :maintenances, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :maintenance_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :favorites, only: [:index]
    resources :cars, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :fuel_efficiencies, only: [:new, :create, :index, :show, :edit, :update, :destroy]

    resources :groups, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resources :group_users, only: [:create, :destroy]
      resources :event_notices, only: [:new, :create]
      get "event_notices" => "event_notices#sent"
      member do
        delete 'remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'
      end
      resources :requests, only: [:create, :update]
    end

    get '/search', to: 'searches#search'
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
    def index
      @users = User.unscoped.without_guest
    end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>All Users List</h1>
      <%= link_to "削除済みユーザー一覧", deleted_index_admin_users_path, class: "btn btn-secondary" %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>ユーザーネーム</th>
            <th>メールアドレス</th>
            <th>状態</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr class="<%= 'table-danger' if user.deleted? %>">
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td>
                <% if user.deleted? %>
                  <span class="text-danger">削除済み</span>
                <% else %>
                  <span class="text-success">有効</span>
                <% end %>
              </td>
              <td>
                <% unless user.guest_user? %>
                  <% if user.deleted? %>
                    <%= link_to '復元',restore_admin_user_path(user),method: :patch,data: { confirm: 'このユーザーを復元しますか？' },class: "btn btn-success" %>
                  <% else %>
                    <%= link_to '削除',admin_user_path(user),method: :delete,data: { confirm: '本当に削除しますか？' },class: "btn btn-danger" %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>